### PR TITLE
Create codeql-analysis.yml

### PR DESCRIPTION
**Pull request by coliff**

### CODE REVIEW

**Comment by coliff** [comment]
I just used the default setup for this - maybe it need to be setup differently… feel free to close if it’s not helpful / needed.

**Comment by DavidWiseman** [comment]
I'm not familiar with CodeQL but it looks like something that would be good to have included.  It looks like this might be having problems with the database project.  I came across a similar issue trying to get the project to build on the github runners. I didn't spend too much time on this, but the DB project needs to be build with msbuild (not cross platform) rather than dotnet build.  
I'm not sure if CodeQL could be configured to exclude the DB project?  Or if it can be configured to use a Windows runner with msbuild?

I'd looked briefly at the option of doing some automated testing with github runners - I need a linux runner as SQL Server is only supported on linux docker.   But I can't build the DB project on linux as it needs ms build.  I did find this workaround which I might explore at some point
https://erikej.github.io/efcore/2020/05/11/ssdt-dacpac-netcore.html
Or another option for testing might be a custom runner for my lab environment.

**Review by DavidWiseman — COMMENTED** [review]
I'm not familiar with CodeQL but it looks like something that would be good to have included. It looks like this might be having problems with the database project. I came across a similar issue trying to get the project to build on the github runners. I didn't spend too much time on this, but the DB project needs to be build with msbuild (not cross platform) rather than dotnet build.
I'm not sure if CodeQL could be configured to exclude the DB project? Or if it can be configured to use a Windows runner with msbuild?

I'd looked briefly at the option of doing some automated testing with github runners - I need a linux runner as SQL Server is only supported on linux docker. But I can't build the DB project on linux as it needs ms build. I did find this workaround which I might explore at some point
https://erikej.github.io/efcore/2020/05/11/ssdt-dacpac-netcore.html
Or another option for testing might be a custom runner for my lab environment.

**Comment by jeffdoolittle** [comment]
Code QL is the language behind GitHub Advanced Security (GHAS) and it is free for open source projects. So definitely something we want to leverage.

**Comment by DavidWiseman** [comment]
This looks like a better solution to get the DB project  to build with dotnet build.  
https://docs.microsoft.com/en-us/sql/azure-data-studio/extensions/sql-database-project-extension-build-from-command-line?view=sql-server-ver15
Opening in ADS makes some changes to the sqlproj file automatically - which will continue to work with both SSDT and ADS and dotnet build from the commandline.  You need some files that some with the SQL projects extension and have to pass that in via the commandline:
dotnet build "<sqlproj file path>" /p:NetCoreBuild=true /p:NETCoreTargetsPath="<DotNet Core build folder>"

**Comment by DavidWiseman** [comment]
I can get everything to build OK on the github runners.  I'll share what I've done when I get chance - tomorrow or Thursday.

**Comment by DavidWiseman** [comment]
Hi @jeffdoolittle  @coliff 

I've managed to get the project to build.  The fixes are on branch  **codeql-analysis-dw** .  Note: I created a new branch with my initials appended as I needed to overwrite.

- The DBA Dash Continuous Integration (ci.yml) workflow is working.  It's just set to build the project. 
- The CodeQL one I don't seem to be able to trigger for some reason.

This branch is codeql-analysis with the changes from main rebased on it - then the changes to get the build to work:

- Created a "CLI" configuration to exclude the DB project and removed the reference to the DB project from the test project.   This means you can do this and build everything except the DB project which was causing the issues:
`dotnet build -c CLI`
- Updated the workflows to use this configuration.  Also, setup the DB to build separate using msbuild.

Would you be able to review the changes and look at the CodeQL workflow?  If you are happy feel free to pull the changes into main.  I'm not sure if you prefer to keep the history or squash the changes to make it neater? 

_Note: It might be possible to get the whole thing running with msbuild but it seemed to have a problem with .NET 6.  Building the DB with dotnet build is also possible - but we need some binaries from azure data studio which isn't ideal.  Or use the first SDK project option which also isn't ideal._

**Comment by jeffdoolittle** [comment]
I typically like to squash but in this case you did all the work but squashing would attribute the work to Christian so let's keep this history this time. 😄

**Comment by DavidWiseman** [comment]
Thanks @jeffdoolittle.  Sorry - I complicated things by creating a new branch and not force pushing to the original one.  We needed some extra changes but they are in now and the github actions are running successfully.

https://github.com/trimble-oss/dba-dash/pull/25

**Pull request merged**
